export const navMenu = [    {
        "name":"Customers",
        "routeTo":"customerView"
    },
    {
        "name":"",
        "routeTo":"shipmentView"
    },
    {
        "name":"Employees",
        "routeTo":"employeeView"
    },
    {
        "name":"Returns",
        "routeTo":"returnsView"
    },
    {
        "name":"Orders",
        "routeTo":"orderView"
    },
]